# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69cd5ced21f13f577d5f9c99cd959d8c608291d85e81419416aeab820f655acd51126926235b5193df9c83030d757bd89aab3e38de9d610a62066f94b1f1791b

test:
  secret_key_base: 852890abda792f9d67df9f9935f1427e9e7a3f1d5927bc35a00a96b5f52c7898bc6f4f0480907c408171fcf95606fe44476c459e5987c686421ccc59f3626bd8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
